changelog:
  categories:
    - title: Enhancement
      labels:
        - enhancement
    - title: Bug Fixes
      labels:
        - fixes
  exclude:
    labels:
      - dependencies
    authors:
      - dependabot