name: Manual Matrix
on: push
jobs:
    print:
        strategy:
            matrix:
                include:
                    - os: ubuntu-latest
                      version: 20
                    - os: macro-latest
                      version: 18
        runs-on: ${{ matrix.os }}
        steps:
            - uses: actions/setup-node@v5
              with:
                node-version: ${{ matrix.version }}
            - run: echo "${RUNNER_OS}" && node --version