name: Release
on:
    push:
        tags:
            - 'v[0-9]+.[0-9]+.[0-9]+'
jobs:
    release:
        runs-on: ubuntu-latest
        env:
            VERSION: ${{ github.ref_name}}
        permissions:
            contents: write
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-go@v5
              with:
                go-version: '1.22'
            - run: |
                go build -ldflags "-X main.version=${VERSION}" \
                -o "${RUNNER_TEMP}/example" go/example/main.go
            - run: |
                gh release create "${VERSION}" --title "${VERSION}" --generate-notes
                gh release upload "${VERSION}" "${RUNNER_TEMP}/example"
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN}}
            - name: Get release notes
              id: get_release_notes
              run: |
                RELEASE_NOTES=$(gh release view "${{ env.VERSION }}" --json body --jq .body)
                echo "::set-output name=notes::${RELEASE_NOTES}"
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            - name: Update release with notes
              run: |
                gh release edit "${{ env.VERSION }}" --notes "${{ steps.get_release_notes.outputs.notes }}"
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}