name: Go Test
on:
    pull_request:
        paths: ['go/**/*.go']
jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-go@v5
              with:
                go-version: '1.22'
<<<<<<< HEAD
            - run: go test ./...
=======
            - run: go test go/excellet/...
>>>>>>> ce8fca758bf2018dd4f07fd3dfcc70291aebaa3b
